using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;

namespace OpenIPC.Viewer.App.Services;

// Tiny ICU-free localizer. Static singleton because XAML's {Binding [Key],
// Source={x:Static svc:Localizer.Instance}} pattern needs a static reference.
// SetLanguage raises PropertyChanged with an empty name ("everything changed")
// so every binding on Localizer.Instance re-reads when the active dict flips —
// no relaunch needed. Note: the WPF "Item[]" indexer convention does NOT work
// here — Avalonia's accessor only re-reads when PropertyName equals the CLR
// indexer name ("Item") or is null/empty, so persistent controls like the
// bottom nav stayed stale on "Item[]". Empty name is the reliable signal.
//
// EN/RU only for now; adding a third language = one more dict + one more
// LangCode value. Missing keys fall back to the key itself, so adding a new
// string in XAML before translating shows up as the key (loud failure mode).
public sealed class Localizer : INotifyPropertyChanged
{
    public static Localizer Instance { get; } = new();

    // _current is left nullable on purpose. Static field init runs in
    // declaration order — Instance (line above) runs before English/Russian
    // are assigned, so any field initializer like `= English` would capture
    // null. By the time anyone reads the indexer, all static initializers
    // for this type have completed, so `?? English` is safe and never null.
    // SetLanguage assigns _current properly once called.
    private IReadOnlyDictionary<string, string>? _current;
    private LangCode _active = LangCode.English;

    public event PropertyChangedEventHandler? PropertyChanged;

    public string this[string key] => (_current ?? English).TryGetValue(key, out var v) ? v : key;
    public LangCode Active => _active;

    public void SetLanguage(LangCode code)
    {
        var resolved = code == LangCode.System ? DetectSystem() : code;
        if (resolved == _active && _current is not null) return;

        _current = resolved switch
        {
            LangCode.Russian => Russian,
            _ => English,
        };
        _active = resolved;
        // Empty/null name = "all properties changed"; Avalonia's INPC accessor
        // re-reads on string.IsNullOrEmpty(PropertyName). "Item[]" would not match.
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));
    }

    private static LangCode DetectSystem()
    {
        var name = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        return name.Equals("ru", System.StringComparison.OrdinalIgnoreCase)
            ? LangCode.Russian
            : LangCode.English;
    }

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Nav.Live"] = "Live",
        ["Nav.Library"] = "Library",
        ["Nav.Recordings"] = "Recordings",
        ["Nav.RecordingsShort"] = "Records",
        ["Nav.Events"] = "Events",
        ["Nav.Analytics"] = "AI",
        ["Nav.Settings"] = "Settings",
        ["Startup.Title"] = "Starting OpenIPC Viewer",
        ["Startup.Preparing"] = "Preparing…",
        ["Startup.Migrating"] = "Initializing database…",
        ["Startup.SyncingConfig"] = "Syncing configuration…",
        ["Startup.StartingServices"] = "Starting services…",
        ["Startup.Ready"] = "Ready",
        ["Startup.Failed"] = "Initialization failed",
        ["Startup.Retry"] = "Retry",
        ["Startup.Exit"] = "Exit",
        ["Tray.Open"] = "Open viewer",
        ["Tray.AddCamera"] = "Add camera…",
        ["Tray.Settings"] = "Settings",
        ["Tray.About"] = "About",
        ["Tray.Exit"] = "Exit",
        ["Analytics.Overview"] = "Engine",
        ["Analytics.Status"] = "Status",
        ["Analytics.Status.NotStarted"] = "Not started",
        ["Analytics.Status.Preparing"] = "Downloading model…",
        ["Analytics.Status.Loading"] = "Loading model…",
        ["Analytics.Status.Ready"] = "Ready",
        ["Analytics.Status.Failed"] = "Failed (see logs)",
        ["Analytics.Provider"] = "Execution provider",
        ["Analytics.ActiveCameras"] = "Active cameras",
        ["Analytics.Processed"] = "Frames processed",
        ["Analytics.Dropped"] = "Frames dropped",
        ["Analytics.Queue"] = "Queue:",
        ["Analytics.Latency"] = "Latency:",
        ["Analytics.Cameras"] = "Cameras with detection",
        ["Analytics.RecentDetections"] = "Recent detections",
        ["Analytics.AllClasses"] = "all classes",

        ["Common.Cancel"] = "Cancel",
        ["Common.Delete"] = "Delete",
        ["Common.Create"] = "Create",
        ["Common.Rename"] = "Rename",
        ["Layouts.NewTitle"] = "New layout",
        ["Layouts.RenameTitle"] = "Rename layout",
        ["Layouts.DeleteTitle"] = "Delete layout",
        ["Layouts.DeleteMessageFormat"] = "Delete layout “{0}”? Cameras stay in your library.",
        ["Layouts.Tooltip.Add"] = "New layout",
        ["Layouts.Tooltip.Rename"] = "Rename layout",
        ["Layouts.Tooltip.Delete"] = "Delete layout",
        ["Layouts.Tooltip.Cameras"] = "Add / remove cameras",
        ["LayoutCameras.WindowTitle"] = "Layout cameras",
        ["LayoutCameras.TitleFormat"] = "Cameras in “{0}”",
        ["LayoutCameras.Empty"] = "No cameras in your library yet",
        ["LayoutCameras.Search"] = "Search cameras…",
        ["Common.Save"] = "Save",
        ["Common.Apply"] = "Apply",
        ["Common.Unknown"] = "(unknown)",
        ["Common.Back"] = "← Back",
        ["Common.Refresh"] = "⟲ Refresh",
        ["Common.Discover"] = "Discover",
        ["Common.AddCamera"] = "+ Add camera",
        ["Common.Loading"] = "Loading…",
        ["Common.Retry"] = "Retry",
        ["Common.Close"] = "Close",
        ["Common.All"] = "All days",

        ["Stream.Connecting"] = "Connecting…",
        ["Stream.Reconnecting"] = "Reconnecting…",
        ["Stream.Disconnected"] = "Disconnected",
        ["Stream.Interrupted"] = "Stream interrupted",
        ["Stream.Unavailable"] = "Stream unavailable",

        ["Health.WindowTitle"] = "Health Center",
        ["Health.Title"] = "Camera health",
        ["Health.Tooltip"] = "Health Center",
        ["Health.Refresh"] = "Refresh",
        ["Health.Empty"] = "No cameras yet.",
        ["Health.Online"] = "online",
        ["Health.Attention"] = "attention",
        ["Health.Offline"] = "offline",
        ["Health.Reason.Ok"] = "Reachable",
        ["Health.Reason.Unreachable"] = "Unreachable",
        ["Health.Reason.Probing"] = "Checking…",
        ["Health.Reason.StreamError"] = "Stream error",
        ["Health.Reason.StreamErrorReachable"] = "Stream wedged (reachable)",
        ["Health.Reason.Connecting"] = "Connecting…",

        ["Library.Title"] = "Cameras",
        ["Library.EmptyTitle"] = "No cameras yet",
        ["Library.RowOpenWeb"] = "Open web",
        ["Library.RowSsh"] = "SSH",
        ["Library.RowFiles"] = "Files",
        ["Library.RowEdit"] = "Edit",
        ["Library.RowDelete"] = "Delete",
        ["Library.RowShowInGrid"] = "Show in grid",
        ["Library.RowDevice"] = "Device",
        ["Firmware.Title"] = "Device maintenance",
        ["Firmware.NoCredentials"] = "No SSH credentials for this camera — add them in Edit to manage the device.",
        ["Firmware.Time"] = "Time",
        ["Firmware.SetFromPc"] = "Set from PC",
        ["Firmware.SyncNtp"] = "Sync NTP",
        ["Firmware.Logs"] = "Logs",
        ["Firmware.Reboot"] = "Reboot",
        ["Firmware.Reboot.Hint"] = "Restarts the camera; the stream drops while it boots.",
        ["Firmware.Reboot.Title"] = "Reboot camera",
        ["Firmware.Reboot.Message"] = "Reboot '{0}'? The stream will drop while it restarts.",
        ["Firmware.Reboot.Confirm"] = "Reboot",
        ["Firmware.Status.TimeLoaded"] = "Time loaded.",
        ["Firmware.Status.TimeSet"] = "Clock set from this PC.",
        ["Firmware.Status.NtpSynced"] = "NTP sync done.",
        ["Firmware.Status.LogLoaded"] = "Log loaded.",
        ["Firmware.Status.Rebooting"] = "Reboot command sent.",
        ["Firmware.Status.Failed"] = "Failed: {0}",
        ["Library.Offline"] = "OFFLINE",
        ["Library.Online"] = "ONLINE",
        ["Library.Attention"] = "ATTENTION",
        ["Library.Checking"] = "CHECKING…",
        ["Library.AllGroups"] = "All groups",
        ["Library.ManageGroups"] = "Groups…",
        ["Library.ScanQr"] = "Scan QR",
        ["Library.ScanQr.PickerTitle"] = "Select QR code image",
        ["Library.ScanQr.NoQrTitle"] = "No QR code found",
        ["Library.ScanQr.NoQrMessage"] = "No QR / barcode could be decoded from the picked image. Try a clearer crop.",
        ["Library.ScanQr.UnsupportedTitle"] = "Unsupported QR payload",
        ["Library.ScanQr.UnsupportedMessage"] = "Expected rtsp://… URL, openipc-viewer://… URI, or JSON object with host/rtsp/credentials fields.",
        ["Library.ScanQr.DecodeFailedTitle"] = "Decode failed",
        ["Library.ScanQr.DecodeFailedFormat"] = "Could not decode the image: {0}",
        ["Library.Dialog.DeleteTitle"] = "Delete camera",
        ["Library.Dialog.DeleteMessage"] = "Delete '{0}'? This cannot be undone.",
        ["Library.Dialog.NewCamerasTitle"] = "New cameras found",
        ["Library.Dialog.NewCamerasMessage"] = "Auto-scan found {0} new camera(s). Open Discovery?",
        ["Library.Dialog.OpenDiscovery"] = "Open Discovery",
        ["Library.Dialog.NotNow"] = "Not now",

        ["Groups.WindowTitle"] = "Manage groups",
        ["Groups.Title"] = "Camera groups",
        ["Groups.Empty"] = "No groups yet",
        ["Groups.NewName"] = "New group name",
        ["Groups.Add"] = "Add",
        ["Groups.Error.CamerasReferenced"] = "Cannot delete: cameras still reference this group.",
        ["Groups.Tooltip.Rename"] = "Rename",
        ["Groups.Tooltip.Confirm"] = "Confirm",
        ["Groups.Tooltip.Delete"] = "Delete",

        ["Welcome.Title"] = "OpenIPC Viewer",
        ["Welcome.Tagline"] = "Cross-platform viewer for OpenIPC IP cameras",
        ["Welcome.Lead"] = "Add your first camera to get started.",
        ["Welcome.Discover"] = "Scan local network (WS-Discovery)",
        ["Welcome.ScanQr"] = "Scan QR code (image file)",
        ["Welcome.AddManually"] = "Add manually (host + RTSP path)",
        ["Welcome.Skip"] = "Skip — I'll add later",
        ["Welcome.WindowTitle"] = "Welcome to OpenIPC Viewer",

        ["Settings.Title"] = "Settings",
        ["Settings.Appearance"] = "Appearance",
        ["Settings.Appearance.Language"] = "Language",
        ["Settings.Appearance.ShowSplash"] = "Show animated splash screen on launch",
        ["Settings.Appearance.CloseToTray"] = "Keep running in the tray when the window is closed",
        ["Settings.Video"] = "Video",
        ["Settings.Recording"] = "Recording",
        ["Settings.Discovery"] = "Discovery",
        ["Settings.Ssh"] = "SSH",
        ["Settings.Advanced"] = "Advanced",
        ["Settings.About"] = "About",
        ["Settings.Ssh.StrictHostKey"] = "Strict host-key checking",
        ["Settings.Ssh.DefaultPort"] = "Default SSH port",
        ["Settings.Ssh.TerminalFontSize"] = "Terminal font size",
        ["Settings.Ssh.MajesticPath"] = "majestic.yaml path",
        ["Settings.Ssh.ResetHostKeys"] = "Forget all host keys",
        ["Settings.Ssh.HostKeysCleared"] = "All pinned host keys were forgotten.",
        ["Settings.Ssh.ResetTitle"] = "Forget host keys",
        ["Settings.Ssh.ResetMessage"] = "Forget all pinned SSH host keys? They will be re-pinned on next connect.",
        ["Settings.Ssh.ResetConfirm"] = "Forget",

        ["Settings.Video.TelemetryOverlay"] = "Show telemetry overlay on live view",
        ["Settings.Video.AutoSdHd"] = "Auto SD/HD (sub in grid, main when full-screen)",
        ["Settings.Video.AiForceCpu"] = "Force CPU for AI analytics (no GPU acceleration)",
        ["Settings.Video.MaxGridSessions"] = "Max concurrent grid sessions",
        ["Settings.Video.RtspTransport"] = "Default RTSP transport",
        ["Settings.Video.NetworkInterface"] = "Network interface (discovery)",
        ["Settings.Video.NetworkInterface.Auto"] = "Auto",
        ["Settings.Video.IdleTimeout"] = "Pause streams after inactivity",
        ["Settings.Video.IdleTimeout.Off"] = "Off",
        ["Settings.Video.IdleTimeout.Minutes"] = "{0} min",
        ["Settings.Video.IdleTimeout.Note"] = "When the window is left open and untouched for this long, all live streams stop to spare the camera network. Any input resumes them. Note: this also pauses motion/AI alerts while suspended.",

        ["Settings.Recording.Directory"] = "Recordings directory",
        ["Settings.Recording.PickFolder"] = "Pick folder…",
        ["Settings.Recording.Reset"] = "Reset to default",
        ["Settings.Recording.Open"] = "Open",

        ["Settings.Discovery.AutoScan"] = "Run WS-Discovery on launch",

        ["Settings.Advanced.VerboseLogging"] = "Verbose logging (debug level)",
        ["Settings.Advanced.RawConfigEditor"] = "Allow risky device tools (raw config editing, file manager)",
        ["Settings.Advanced.SingleInstance"] = "Single instance only (a repeat launch focuses the running window)",
        ["Settings.Advanced.OpenAppData"] = "Open app data folder",

        ["Settings.About.Repository"] = "GitHub repository →",
        ["Settings.Report.Button"] = "Report a problem",
        ["Settings.Report.OpenLogs"] = "Open logs folder",
        ["Settings.Report.BodyDescribe"] = "Describe the problem",

        ["Settings.Backup.Section"] = "Backup & restore",
        ["Settings.Backup.Description"] = "Export cameras and layouts to a JSON file, or import them on another machine. Passwords are never exported.",
        ["Settings.Backup.Export"] = "Export…",
        ["Settings.Backup.Import"] = "Import…",
        ["Settings.Backup.ExportTitle"] = "Export configuration",
        ["Settings.Backup.ImportTitle"] = "Import configuration",
        ["Settings.Backup.ImportConfirm"] = "Import",
        ["Settings.Backup.ConfirmFormat"] = "Add {0} cameras ({1} overwritten) and {2} layouts?",
        ["Settings.Backup.Exported"] = "Configuration exported.",
        ["Settings.Backup.Imported"] = "Configuration imported.",
        ["Settings.Backup.FailedFormat"] = "Failed: {0}",

        ["Settings.ConfigSync.Section"] = "Network config auto-update",
        ["Settings.ConfigSync.Description"] = "On startup, mirror cameras and layouts from a shared config file (a local or network path). The file is the source of truth — cameras and layouts not in it are removed on this machine. If the path is unreachable, the last working config keeps running.",
        ["Settings.ConfigSync.Enable"] = "Auto-update config from a path",
        ["Settings.ConfigSync.PathLabel"] = "Config path",
        ["Settings.ConfigSync.PathPlaceholder"] = "\\\\server\\share\\openipc-config.json",
        ["Settings.ConfigSync.MirrorWarning"] = "Mirror mode: local cameras and layouts absent from the file are deleted. Passwords are not synced — enter them once per machine.",
        ["Settings.ConfigSync.IncludeCreds"] = "Sync camera passwords (encrypted)",
        ["Settings.ConfigSync.Passphrase"] = "Shared passphrase",
        ["Settings.ConfigSync.PassphraseHint"] = "The same passphrase must be set on every machine and used when exporting the file. It is stored encrypted locally and never written to the JSON.",
        ["Settings.ConfigSync.SyncNow"] = "Sync now",
        ["Settings.ConfigSync.Disabled"] = "Auto-update is off or no path is set.",
        ["Settings.ConfigSync.Unreachable"] = "Path unreachable: {0}. Keeping the last working config.",
        ["Settings.ConfigSync.Unchanged"] = "Already up to date.",
        ["Settings.ConfigSync.AppliedFormat"] = "Synced: +{0} added, {1} updated, {2} removed cameras, {3} layouts.",

        ["Settings.Notifications.Section"] = "Notifications",
        ["Settings.Notifications.Test"] = "Send test notification",
        ["Settings.Notifications.TestTitle"] = "Test notification",
        ["Settings.Notifications.TestBody"] = "If you can see this, desktop notifications work.",
        ["Settings.Notifications.Enable"] = "Enable notifications",
        ["Settings.Notifications.Motion"] = "Motion events",
        ["Settings.Notifications.Detection"] = "Object detections",
        ["Settings.Notifications.Cooldown"] = "Cooldown per camera (sec)",
        ["Settings.Notifications.QuietHours"] = "Quiet hours",
        ["Settings.Notifications.From"] = "From",
        ["Settings.Notifications.To"] = "to",

        ["Snapshot.Saved"] = "Saved →",
        ["Snapshot.Open"] = "Open",
        ["Snapshot.Copy"] = "Copy",
        ["Snapshot.SaveAs"] = "Save as…",

        ["CameraEditor.Title.Add"] = "Add camera",
        ["CameraEditor.Title.Edit"] = "Edit camera",
        ["CameraEditor.Label.Name"] = "Name",
        ["CameraEditor.Label.Host"] = "Host",
        ["CameraEditor.Label.HttpPort"] = "HTTP port",
        ["CameraEditor.Label.OnvifPort"] = "ONVIF port (optional)",
        ["CameraEditor.Label.RtspMain"] = "RTSP main URI",
        ["CameraEditor.Label.RtspSub"] = "RTSP sub URI (optional)",
        ["CameraEditor.Label.Username"] = "Username",
        ["CameraEditor.Label.Password"] = "Password",
        ["CameraEditor.Label.Group"] = "Group",
        ["CameraEditor.Label.SshSection"] = "SSH (optional)",
        ["CameraEditor.Label.StreamQuality"] = "Grid stream quality",
        ["CameraEditor.Quality.Auto"] = "Auto (SD/HD)",
        ["CameraEditor.Quality.AlwaysHd"] = "Always HD (main)",
        ["CameraEditor.Quality.AlwaysSd"] = "Always SD (sub)",
        ["CameraEditor.Analytics.Section"] = "AI analytics",
        ["CameraEditor.Analytics.Enable"] = "Enable object detection",
        ["CameraEditor.Analytics.Classes"] = "Classes",
        ["CameraEditor.Analytics.Threshold"] = "Confidence threshold",
        ["CameraEditor.Analytics.Fps"] = "Analysis FPS",
        ["CameraEditor.Analytics.AutoRecord"] = "Auto-record on detection",
        ["CameraEditor.Analytics.PostEvent"] = "Keep recording after (s)",
        ["CameraEditor.Placeholder.Name"] = "Front door",
        ["CameraEditor.Placeholder.Host"] = "192.168.1.10",
        ["CameraEditor.Placeholder.OnvifPort"] = "8899",
        ["CameraEditor.Placeholder.RtspMain"] = "rtsp://192.168.1.10/",
        ["CameraEditor.Placeholder.RtspSub"] = "rtsp://192.168.1.10/stream1",
        ["CameraEditor.Placeholder.Username"] = "admin",
        ["CameraEditor.Placeholder.SshUser"] = "SSH user (reuse main if blank)",
        ["CameraEditor.Placeholder.SshPassword"] = "SSH password (reuse main if blank)",
        ["CameraEditor.Placeholder.SshPort"] = "22",
        ["CameraEditor.NoGroup"] = "(no group)",
        ["CameraEditor.Button.AutoDeriveRtsp"] = "Auto from host",
        ["CameraEditor.Button.RtspTemplates"] = "Templates ▾",
        ["CameraEditor.Tooltip.RtspTemplates"] = "Fill in the RTSP URLs used by a specific camera vendor",
        ["CameraEditor.Button.TestConnection"] = "Test connection",
        ["CameraEditor.Status.Connecting"] = "Connecting…",
        ["CameraEditor.Status.OkFormat"] = "OK — {0}x{1}",
        ["CameraEditor.Status.Timeout"] = "Timeout (8s)",
        ["CameraEditor.Status.FailedFormat"] = "Failed: {0}",
        ["CameraEditor.Error.NameRequired"] = "Name is required.",
        ["CameraEditor.Error.HostRequired"] = "Host is required.",
        ["CameraEditor.Error.RtspMainInvalid"] = "RTSP main URI is not a valid absolute URI.",
        ["CameraEditor.Error.RtspSubInvalid"] = "RTSP sub URI is not a valid absolute URI.",
        ["CameraEditor.Error.OnvifPortInvalid"] = "ONVIF port must be between 1 and 65535.",
        ["CameraEditor.Error.HttpPortInvalid"] = "HTTP port must be between 1 and 65535.",
        ["CameraEditor.Error.SshPortInvalid"] = "SSH port must be between 1 and 65535.",
        ["CameraEditor.Error.SshCredsIncomplete"] = "Enter both SSH username and password, or leave both blank.",
        ["Terminal.Connecting"] = "Connecting…",
        ["Terminal.NoCreds"] = "No SSH credentials set for this camera.",
        ["Terminal.FailedFormat"] = "SSH error: {0}",
        ["Ssh.HostKeyChanged.Title"] = "SSH host key changed",
        ["Ssh.HostKeyChanged.Message"] = "The SSH key presented by {0} does not match the one pinned earlier.\n\nNew:    {1}\nPinned: {2}\n\nThis is expected if the camera was reflashed or replaced — but could also mean someone is intercepting the connection. Trust the new key and continue?",
        ["Ssh.HostKeyChanged.Trust"] = "Trust new key",
        ["FileManager.Title"] = "Files",
        ["FileManager.Connecting"] = "Connecting…",
        ["FileManager.NoCreds"] = "No SSH credentials set for this camera.",
        ["FileManager.FailedFormat"] = "Error: {0}",
        ["FileManager.Refresh"] = "Refresh",
        ["FileManager.NewFolder"] = "New folder",
        ["FileManager.Upload"] = "Upload",
        ["FileManager.Download"] = "Download",
        ["FileManager.SaveTitle"] = "Save file as",
        ["FileManager.UploadTitle"] = "Pick a file to upload",
        ["FileManager.NewFolderTitle"] = "New folder name",
        ["FileManager.Downloading"] = "Downloading…",
        ["FileManager.Uploading"] = "Uploading…",
        ["FileManager.TransferDone"] = "Done.",
        ["FileManager.DeleteProtected"] = "Refusing to delete a root-level path.",
        ["FileManager.DeleteTitle"] = "Delete",
        ["FileManager.DeleteMessage"] = "Delete \"{0}\" from the camera?",
        ["FileManager.Hint"] = "Tap a folder to open, a file to download.",

        ["Discovery.Title"] = "Discover cameras",
        ["Discovery.Header"] = "Discover ONVIF cameras",
        ["Discovery.Button.Scan"] = "Scan",
        ["Discovery.Button.AddSelected"] = "Add selected",
        ["Discovery.Status.Initial"] = "Click Scan to find cameras on the LAN (ONVIF + mDNS). Deep scan also sweeps the ticked subnets — including ones only reachable through a VPN.",
        ["Discovery.Status.Scanning"] = "Scanning…",
        ["Discovery.Status.ScanningRangeFormat"] = "Scanning {0} ({1} addresses)…",
        ["Discovery.Status.NoResponse"] = "No cameras responded. Check multicast / firewall.",
        ["Discovery.Status.FoundFormat"] = "Found {0} camera(s).",
        ["Discovery.Status.Cancelled"] = "Scan cancelled.",
        ["Discovery.Status.ScanFailedFormat"] = "Scan failed: {0}",
        ["Discovery.Status.ProbingFormat"] = "Probing {0}…",
        ["Discovery.Status.ProbeOkFormat"] = "OK — {0} {1}",
        ["Discovery.Status.ProbeFailedFormat"] = "Probe failed: {0}",
        ["Discovery.Status.ManualAdd"] = "No ONVIF — review the stream URL in the editor.",
        ["Discovery.DeepScan"] = "Deep scan (slower)",
        ["Discovery.IpRange.Placeholder"] = "another range, if you need one — 192.168.5.0/24, 10.0.0.10-60",
        ["Discovery.Target.DetailFormat"] = "{0} · {1} · {2} addresses",
        ["Discovery.Target.Local"] = "this machine's network",
        ["Discovery.Target.Routed"] = "routed — VPN or another VLAN",
        ["Discovery.Sweep.SummaryFormat"] = "Deep scan will knock on {0} address(es).",
        ["Discovery.IpRange.Invalid"] = "Not a valid IP range. Use 192.168.1.0/24, 192.168.1.10-200, or a single address.",
        ["Discovery.IpRange.TooLargeFormat"] = "Range too wide — at most {0} addresses per scan.",
        ["Discovery.UnknownModel"] = "(unknown model)",
        ["Discovery.AlreadyAdded"] = "added",
        ["Discovery.ReuseCreds"] = "Use these credentials for all cameras",
        ["Discovery.Confidence.Low"] = "low",
        ["Discovery.Confidence.Medium"] = "medium",
        ["Discovery.Confidence.High"] = "high",

        ["RawConfigEditor.Title"] = "Edit raw Majestic config",
        ["RawConfigEditor.InvalidJsonFormat"] = "Invalid JSON: {0}",

        ["CameraPage.Rtmp.Toggle"] = "RTMP push",
        ["CameraPage.Rtmp.UrlPlaceholder"] = "rtmp://server/stream-key",

        ["CameraPage.Majestic.Resolution"] = "Res",
        ["CameraPage.Majestic.Codec"] = "Codec",
        ["CameraPage.Majestic.Fps"] = "FPS",
        ["CameraPage.Majestic.Bitrate"] = "Bitrate",
        ["CameraPage.Majestic.Profile"] = "Profile",
        ["CameraPage.Majestic.NightPrefix"] = "night:",
        ["CameraPage.Majestic.ViewRaw"] = "View raw",
        ["CameraPage.Majestic.EditRaw"] = "Edit raw",
        ["CameraPage.Majestic.EditRawSsh"] = "Edit via SSH",
        ["CameraPage.Majestic.AllSettings"] = "All settings",
        ["CameraPage.Majestic.ApplyAll"] = "Apply settings",
        ["CameraPage.Majestic.NoChanges"] = "No changes to apply",
        ["CameraPage.Majestic.RestartHint"] = "Changing this restarts the video stream",
        ["CameraPage.Majestic.Isp"] = "Live ISP",
        ["CameraPage.Majestic.IspApply"] = "Apply ISP (live)",
        ["CameraPage.Majestic.IspApplied"] = "ISP applied — no restart",
        ["CameraPage.Majestic.IspEmpty"] = "This firmware exposes no ISP settings.",
        ["CameraPage.Majestic.Metrics"] = "Metrics",
        ["CameraPage.Majestic.MetricsRefresh"] = "Refresh",
        ["CameraPage.Majestic.MetricsEmpty"] = "No metrics returned.",
        ["CameraPage.Majestic.Search"] = "Filter fields…",
        ["CameraPage.Majestic.Revert"] = "Revert to camera value",
        ["CameraPage.Majestic.RevertSection"] = "Revert section",
        ["CameraPage.SshNoCreds"] = "No SSH credentials set for this camera.",
        ["CameraPage.NightMode.Day"] = "Day",
        ["CameraPage.NightMode.Night"] = "Night",
        ["CameraPage.NightMode.Auto"] = "Auto",
        ["CameraPage.Preset.Placeholder"] = "preset name",
        ["CameraPage.Preset.Save"] = "+ Save",
        ["CameraPage.Snapshot"] = "Snapshot",
        ["CameraPage.Stop"] = "■ Stop",
        ["CameraPage.ApplyingStatus"] = "Applying…",
        ["CameraPage.ApplyingRawStatus"] = "Applying raw config…",
        ["CameraPage.AppliedRestarting"] = "Applied. Restarting stream…",
        ["CameraPage.ApplyDone"] = "Done.",
        ["CameraPage.ApplyFailedFormat"] = "Failed: {0}",
        ["CameraPage.RecordingFailedFormat"] = "Recording failed: {0}",
        ["CameraPage.SnapshotFailedFormat"] = "Snapshot failed: {0}",
        ["CameraPage.Tooltip.Listen"] = "Listen to camera audio",
        ["CameraPage.Tooltip.Mute"] = "Mute audio",
        ["CameraPage.Tooltip.Volume"] = "Volume",
        ["CameraPage.Audio.DisabledHint"] = "Audio is off on this camera",
        ["CameraPage.Audio.Enable"] = "Enable audio",
        ["CameraPage.Audio.Enabling"] = "Enabling…",
        ["CameraPage.Tooltip.Talk"] = "Talk to camera (push-to-talk)",
        ["CameraPage.Talk.Unsupported"] = "This camera has no two-way audio.",
        ["CameraPage.OpenSnapshotFailedFormat"] = "Open snapshot failed: {0}",
        ["CameraPage.CopySnapshotFailedFormat"] = "Copy snapshot failed: {0}",
        ["CameraPage.SaveSnapshotFailedFormat"] = "Save snapshot failed: {0}",
        ["CameraPage.Tooltip.RemovePreset"] = "Remove preset",

        ["Snapshot.SaveAsTitle"] = "Save snapshot",

        ["Snapshots.Title"] = "Snapshots",
        ["Snapshots.AllCameras"] = "All cameras",
        ["Snapshots.PresetAll"] = "All",
        ["Snapshots.PresetToday"] = "Today",
        ["Snapshots.Preset7"] = "7 days",
        ["Snapshots.Preset30"] = "30 days",
        ["Snapshots.SortNewest"] = "Newest first",
        ["Snapshots.SortOldest"] = "Oldest first",
        ["Snapshots.Empty"] = "No snapshots yet",
        ["Snapshots.LoadError"] = "Couldn't load snapshots",
        ["Snapshots.SelectedFormat"] = "{0} selected",
        ["Snapshots.Dialog.DeleteTitle"] = "Delete snapshots",
        ["Snapshots.Dialog.DeleteOneMessage"] = "Delete this snapshot? This can't be undone.",
        ["Snapshots.Dialog.DeleteManyMessageFormat"] = "Delete {0} snapshots? This can't be undone.",

        ["Viewer.ZoomIn"] = "Zoom in",
        ["Viewer.ZoomOut"] = "Zoom out",
        ["Viewer.Fit"] = "Fit",
        ["Viewer.RotateLeft"] = "Rotate left",
        ["Viewer.RotateRight"] = "Rotate right",
        ["Viewer.FlipH"] = "Flip horizontal",
        ["Viewer.FlipV"] = "Flip vertical",
        ["Viewer.Slideshow"] = "Slideshow",
        ["Viewer.Copy"] = "Copy",
        ["Viewer.Properties"] = "Details",
        ["Viewer.Prev"] = "Previous",
        ["Viewer.Next"] = "Next",
        ["Viewer.Edit"] = "Edit",
        ["Viewer.Share"] = "Share",
        ["Viewer.Reveal"] = "Reveal",
        ["Snapshots.Share"] = "Share",
        ["Snapshots.Reveal"] = "Reveal",

        ["Edit.Arrow"] = "Arrow",
        ["Edit.Rect"] = "Box",
        ["Edit.Text"] = "Text",
        ["Edit.Crop"] = "Crop",
        ["Edit.Undo"] = "Undo",
        ["Edit.Save"] = "Save copy",
        ["Edit.TextPrompt"] = "Annotation text",
        ["Edit.AddText"] = "Add",

        ["Grid.EmptySlot"] = "no camera",
        ["Grid.Tooltip.Fullscreen"] = "Fullscreen grid (F11) — Esc to exit",
        ["Grid.Tooltip.Stills"] = "Stills mode — periodic snapshots instead of live video",
        ["Tile.Snapshot"] = "Snapshot (HD)",

        ["Welcome.Language"] = "Language",

        ["Recordings.Dialog.DeleteTitle"] = "Delete recording",
        ["Recordings.Dialog.DeleteMessageFormat"] = "Delete {0}? The MP4 file will be removed.",
        ["Recordings.Empty"] = "No recordings yet. Hit ● REC on a camera page to start.",
        ["Recordings.Live"] = "live",
        ["Recordings.LoadError"] = "Could not load recordings",
        ["Recordings.MarkIn"] = "Set In",
        ["Recordings.MarkOut"] = "Set Out",
        ["Recordings.Precise"] = "Precise",
        ["Recordings.Export"] = "Export",
        ["Recordings.ExportTitle"] = "Export clip",

        ["Events.Button.SimulateMotion"] = "Simulate motion",
        ["Events.Empty"] = "No events yet. Hit Simulate motion to push one through the pipeline.",
        ["Events.AllCameras"] = "All cameras",
        ["Events.Open"] = "open",

        ["Lang.System"] = "System",
        ["Lang.English"] = "English",
        ["Lang.Russian"] = "Русский",
    };

    private static readonly IReadOnlyDictionary<string, string> Russian = new Dictionary<string, string>
    {
        ["Nav.Live"] = "Эфир",
        ["Nav.Library"] = "Камеры",
        ["Nav.Recordings"] = "Записи",
        ["Nav.RecordingsShort"] = "Записи",
        ["Nav.Events"] = "События",
        ["Nav.Analytics"] = "ИИ",
        ["Nav.Settings"] = "Настройки",
        ["Startup.Title"] = "Запуск OpenIPC Viewer",
        ["Startup.Preparing"] = "Подготовка…",
        ["Startup.Migrating"] = "Инициализация базы данных…",
        ["Startup.SyncingConfig"] = "Синхронизация конфигурации…",
        ["Startup.StartingServices"] = "Запуск служб…",
        ["Startup.Ready"] = "Готово",
        ["Startup.Failed"] = "Ошибка инициализации",
        ["Startup.Retry"] = "Повторить",
        ["Startup.Exit"] = "Выход",
        ["Tray.Open"] = "Открыть",
        ["Tray.AddCamera"] = "Добавить камеру…",
        ["Tray.Settings"] = "Настройки",
        ["Tray.About"] = "О программе",
        ["Tray.Exit"] = "Выход",
        ["Analytics.Overview"] = "Движок",
        ["Analytics.Status"] = "Статус",
        ["Analytics.Status.NotStarted"] = "Не запущен",
        ["Analytics.Status.Preparing"] = "Скачивание модели…",
        ["Analytics.Status.Loading"] = "Загрузка модели…",
        ["Analytics.Status.Ready"] = "Готов",
        ["Analytics.Status.Failed"] = "Ошибка (см. логи)",
        ["Analytics.Provider"] = "Провайдер выполнения",
        ["Analytics.ActiveCameras"] = "Активные камеры",
        ["Analytics.Processed"] = "Кадров обработано",
        ["Analytics.Dropped"] = "Кадров отброшено",
        ["Analytics.Queue"] = "Очередь:",
        ["Analytics.Latency"] = "Задержка:",
        ["Analytics.Cameras"] = "Камеры с детекцией",
        ["Analytics.RecentDetections"] = "Недавние детекции",
        ["Analytics.AllClasses"] = "все классы",

        ["Common.Cancel"] = "Отмена",
        ["Common.Delete"] = "Удалить",
        ["Common.Create"] = "Создать",
        ["Common.Rename"] = "Переименовать",
        ["Layouts.NewTitle"] = "Новая раскладка",
        ["Layouts.RenameTitle"] = "Переименовать раскладку",
        ["Layouts.DeleteTitle"] = "Удалить раскладку",
        ["Layouts.DeleteMessageFormat"] = "Удалить раскладку «{0}»? Камеры останутся в библиотеке.",
        ["Layouts.Tooltip.Add"] = "Новая раскладка",
        ["Layouts.Tooltip.Rename"] = "Переименовать раскладку",
        ["Layouts.Tooltip.Delete"] = "Удалить раскладку",
        ["Layouts.Tooltip.Cameras"] = "Добавить / убрать камеры",
        ["LayoutCameras.WindowTitle"] = "Камеры раскладки",
        ["LayoutCameras.TitleFormat"] = "Камеры в «{0}»",
        ["LayoutCameras.Empty"] = "В библиотеке пока нет камер",
        ["LayoutCameras.Search"] = "Поиск камер…",
        ["Common.Save"] = "Сохранить",
        ["Common.Apply"] = "Применить",
        ["Common.Unknown"] = "(неизвестно)",
        ["Common.Back"] = "← Назад",
        ["Common.Refresh"] = "⟲ Обновить",
        ["Common.Discover"] = "Поиск",
        ["Common.AddCamera"] = "+ Добавить камеру",
        ["Common.Loading"] = "Загрузка…",
        ["Common.Retry"] = "Повторить",
        ["Common.Close"] = "Закрыть",
        ["Common.All"] = "Все дни",

        ["Stream.Connecting"] = "Подключение…",
        ["Stream.Reconnecting"] = "Переподключение…",
        ["Stream.Disconnected"] = "Нет соединения",
        ["Stream.Interrupted"] = "Поток прерван",
        ["Stream.Unavailable"] = "Поток недоступен",

        ["Health.WindowTitle"] = "Центр состояния",
        ["Health.Title"] = "Состояние камер",
        ["Health.Tooltip"] = "Центр состояния",
        ["Health.Refresh"] = "Обновить",
        ["Health.Empty"] = "Камер пока нет.",
        ["Health.Online"] = "онлайн",
        ["Health.Attention"] = "внимание",
        ["Health.Offline"] = "офлайн",
        ["Health.Reason.Ok"] = "Доступна",
        ["Health.Reason.Unreachable"] = "Недоступна",
        ["Health.Reason.Probing"] = "Проверка…",
        ["Health.Reason.StreamError"] = "Ошибка потока",
        ["Health.Reason.StreamErrorReachable"] = "Поток завис (доступна)",
        ["Health.Reason.Connecting"] = "Подключение…",

        ["Library.Title"] = "Камеры",
        ["Library.EmptyTitle"] = "Камер пока нет",
        ["Library.RowOpenWeb"] = "Веб-интерфейс",
        ["Library.RowSsh"] = "SSH",
        ["Library.RowFiles"] = "Файлы",
        ["Library.RowEdit"] = "Изменить",
        ["Library.RowDelete"] = "Удалить",
        ["Library.RowShowInGrid"] = "В гриде",
        ["Library.RowDevice"] = "Устройство",
        ["Firmware.Title"] = "Обслуживание устройства",
        ["Firmware.NoCredentials"] = "У камеры нет SSH-доступа — добавьте логин/пароль в «Изменить», чтобы управлять устройством.",
        ["Firmware.Time"] = "Время",
        ["Firmware.SetFromPc"] = "С компьютера",
        ["Firmware.SyncNtp"] = "Синхр. NTP",
        ["Firmware.Logs"] = "Логи",
        ["Firmware.Reboot"] = "Перезагрузка",
        ["Firmware.Reboot.Hint"] = "Перезагружает камеру; поток пропадёт на время загрузки.",
        ["Firmware.Reboot.Title"] = "Перезагрузить камеру",
        ["Firmware.Reboot.Message"] = "Перезагрузить «{0}»? Поток пропадёт на время перезапуска.",
        ["Firmware.Reboot.Confirm"] = "Перезагрузить",
        ["Firmware.Status.TimeLoaded"] = "Время получено.",
        ["Firmware.Status.TimeSet"] = "Часы установлены с этого ПК.",
        ["Firmware.Status.NtpSynced"] = "NTP-синхронизация выполнена.",
        ["Firmware.Status.LogLoaded"] = "Лог загружен.",
        ["Firmware.Status.Rebooting"] = "Команда перезагрузки отправлена.",
        ["Firmware.Status.Failed"] = "Ошибка: {0}",
        ["Library.Offline"] = "ОФЛАЙН",
        ["Library.Online"] = "ОНЛАЙН",
        ["Library.Attention"] = "ВНИМАНИЕ",
        ["Library.Checking"] = "ПРОВЕРКА…",
        ["Library.AllGroups"] = "Все группы",
        ["Library.ManageGroups"] = "Группы…",
        ["Library.ScanQr"] = "Сканировать QR",
        ["Library.ScanQr.PickerTitle"] = "Выберите изображение QR-кода",
        ["Library.ScanQr.NoQrTitle"] = "QR-код не найден",
        ["Library.ScanQr.NoQrMessage"] = "В выбранном изображении не удалось распознать QR / штрих-код. Попробуйте более чёткий кадр.",
        ["Library.ScanQr.UnsupportedTitle"] = "Неподдерживаемый payload",
        ["Library.ScanQr.UnsupportedMessage"] = "Ожидается rtsp://… URL, openipc-viewer://… URI или JSON-объект с полями host/rtsp/credentials.",
        ["Library.ScanQr.DecodeFailedTitle"] = "Не удалось декодировать",
        ["Library.ScanQr.DecodeFailedFormat"] = "Ошибка декодирования: {0}",
        ["Library.Dialog.DeleteTitle"] = "Удалить камеру",
        ["Library.Dialog.DeleteMessage"] = "Удалить «{0}»? Это нельзя отменить.",
        ["Library.Dialog.NewCamerasTitle"] = "Найдены новые камеры",
        ["Library.Dialog.NewCamerasMessage"] = "Автопоиск нашёл новых камер: {0}. Открыть Discovery?",
        ["Library.Dialog.OpenDiscovery"] = "Открыть Discovery",
        ["Library.Dialog.NotNow"] = "Не сейчас",

        ["Groups.WindowTitle"] = "Управление группами",
        ["Groups.Title"] = "Группы камер",
        ["Groups.Empty"] = "Групп пока нет",
        ["Groups.NewName"] = "Название новой группы",
        ["Groups.Add"] = "Добавить",
        ["Groups.Error.CamerasReferenced"] = "Нельзя удалить: камеры всё ещё ссылаются на эту группу.",
        ["Groups.Tooltip.Rename"] = "Переименовать",
        ["Groups.Tooltip.Confirm"] = "Подтвердить",
        ["Groups.Tooltip.Delete"] = "Удалить",

        ["Welcome.Title"] = "OpenIPC Viewer",
        ["Welcome.Tagline"] = "Кросс-платформенный просмотрщик IP-камер OpenIPC",
        ["Welcome.Lead"] = "Добавьте первую камеру, чтобы начать.",
        ["Welcome.Discover"] = "Найти в локальной сети (WS-Discovery)",
        ["Welcome.ScanQr"] = "Сканировать QR-код (файл изображения)",
        ["Welcome.AddManually"] = "Ввести вручную (host + RTSP)",
        ["Welcome.Skip"] = "Пропустить — добавлю позже",
        ["Welcome.WindowTitle"] = "Добро пожаловать в OpenIPC Viewer",

        ["Settings.Title"] = "Настройки",
        ["Settings.Appearance"] = "Внешний вид",
        ["Settings.Appearance.Language"] = "Язык",
        ["Settings.Appearance.ShowSplash"] = "Показывать анимированную заставку при запуске",
        ["Settings.Appearance.CloseToTray"] = "При закрытии окна оставаться в трее",
        ["Settings.Video"] = "Видео",
        ["Settings.Recording"] = "Запись",
        ["Settings.Discovery"] = "Поиск",
        ["Settings.Ssh"] = "SSH",
        ["Settings.Advanced"] = "Дополнительно",
        ["Settings.Ssh.StrictHostKey"] = "Строгая проверка host-key",
        ["Settings.Ssh.DefaultPort"] = "SSH-порт по умолчанию",
        ["Settings.Ssh.TerminalFontSize"] = "Размер шрифта терминала",
        ["Settings.Ssh.MajesticPath"] = "Путь к majestic.yaml",
        ["Settings.Ssh.ResetHostKeys"] = "Забыть все host-ключи",
        ["Settings.Ssh.HostKeysCleared"] = "Все запомненные host-ключи забыты.",
        ["Settings.Ssh.ResetTitle"] = "Забыть host-ключи",
        ["Settings.Ssh.ResetMessage"] = "Забыть все запомненные SSH host-ключи? Они будут запомнены заново при следующем подключении.",
        ["Settings.Ssh.ResetConfirm"] = "Забыть",
        ["Settings.About"] = "О приложении",

        ["Settings.Video.TelemetryOverlay"] = "Показывать телеметрию на видео",
        ["Settings.Video.AutoSdHd"] = "Авто SD/HD (sub в гриде, main на весь экран)",
        ["Settings.Video.AiForceCpu"] = "Только CPU для ИИ-аналитики (без GPU-ускорения)",
        ["Settings.Video.MaxGridSessions"] = "Максимум потоков в гриде",
        ["Settings.Video.RtspTransport"] = "RTSP-транспорт по умолчанию",
        ["Settings.Video.NetworkInterface"] = "Сетевой интерфейс (поиск)",
        ["Settings.Video.NetworkInterface.Auto"] = "Авто",
        ["Settings.Video.IdleTimeout"] = "Останавливать потоки при простое",
        ["Settings.Video.IdleTimeout.Off"] = "Выкл.",
        ["Settings.Video.IdleTimeout.Minutes"] = "{0} мин",
        ["Settings.Video.IdleTimeout.Note"] = "Если окно оставлено открытым и с ним не взаимодействуют это время, все живые потоки останавливаются, чтобы не грузить сеть камер. Любой ввод возобновляет их. Учтите: на время паузы также приостанавливаются уведомления о движении/ИИ-детекции.",

        ["Settings.Recording.Directory"] = "Папка записей",
        ["Settings.Recording.PickFolder"] = "Выбрать…",
        ["Settings.Recording.Reset"] = "Сбросить",
        ["Settings.Recording.Open"] = "Открыть",

        ["Settings.Discovery.AutoScan"] = "Запускать WS-Discovery при старте",

        ["Settings.Advanced.VerboseLogging"] = "Подробные логи (debug)",
        ["Settings.Advanced.RawConfigEditor"] = "Разрешить рискованные инструменты (raw-конфиг, файловый менеджер)",
        ["Settings.Advanced.SingleInstance"] = "Запрещать запуск второй копии (повторный запуск откроет это окно)",
        ["Settings.Advanced.OpenAppData"] = "Открыть папку данных",

        ["Settings.About.Repository"] = "Репозиторий на GitHub →",
        ["Settings.Report.Button"] = "Сообщить о проблеме",
        ["Settings.Report.OpenLogs"] = "Открыть папку логов",
        ["Settings.Report.BodyDescribe"] = "Опишите проблему",

        ["Settings.Backup.Section"] = "Бэкап и восстановление",
        ["Settings.Backup.Description"] = "Выгрузить камеры и раскладки в JSON-файл или импортировать на другой машине. Пароли не экспортируются.",
        ["Settings.Backup.Export"] = "Экспорт…",
        ["Settings.Backup.Import"] = "Импорт…",
        ["Settings.Backup.ExportTitle"] = "Экспорт конфигурации",
        ["Settings.Backup.ImportTitle"] = "Импорт конфигурации",
        ["Settings.Backup.ImportConfirm"] = "Импортировать",
        ["Settings.Backup.ConfirmFormat"] = "Добавить {0} камер ({1} перезаписано) и {2} раскладок?",
        ["Settings.Backup.Exported"] = "Конфигурация экспортирована.",
        ["Settings.Backup.Imported"] = "Конфигурация импортирована.",
        ["Settings.Backup.FailedFormat"] = "Ошибка: {0}",

        ["Settings.ConfigSync.Section"] = "Автообновление конфига из сети",
        ["Settings.ConfigSync.Description"] = "При запуске синхронизирует камеры и раскладки из общего файла конфигурации (локальный или сетевой путь). Файл — источник истины: камеры и раскладки, которых в нём нет, удаляются на этой машине. Если путь недоступен, продолжает работать последний рабочий конфиг.",
        ["Settings.ConfigSync.Enable"] = "Автообновлять конфиг из пути",
        ["Settings.ConfigSync.PathLabel"] = "Путь к конфигу",
        ["Settings.ConfigSync.PathPlaceholder"] = "\\\\сервер\\папка\\openipc-config.json",
        ["Settings.ConfigSync.MirrorWarning"] = "Режим зеркала: локальные камеры и раскладки, которых нет в файле, удаляются. Пароли не синхронизируются — введите их один раз на каждой машине.",
        ["Settings.ConfigSync.IncludeCreds"] = "Синхронизировать пароли камер (шифрование)",
        ["Settings.ConfigSync.Passphrase"] = "Общий пароль-ключ",
        ["Settings.ConfigSync.PassphraseHint"] = "Один и тот же ключ нужно задать на каждой машине и указать при экспорте файла. Хранится локально в зашифрованном виде, в JSON не пишется.",
        ["Settings.ConfigSync.SyncNow"] = "Синхронизировать сейчас",
        ["Settings.ConfigSync.Disabled"] = "Автообновление выключено или путь не задан.",
        ["Settings.ConfigSync.Unreachable"] = "Путь недоступен: {0}. Используется последний рабочий конфиг.",
        ["Settings.ConfigSync.Unchanged"] = "Уже актуально.",
        ["Settings.ConfigSync.AppliedFormat"] = "Синхронизировано: +{0} добавлено, {1} обновлено, {2} удалено камер, {3} раскладок.",

        ["Settings.Notifications.Section"] = "Уведомления",
        ["Settings.Notifications.Test"] = "Отправить тестовое уведомление",
        ["Settings.Notifications.TestTitle"] = "Тестовое уведомление",
        ["Settings.Notifications.TestBody"] = "Если вы это видите — уведомления на рабочем столе работают.",
        ["Settings.Notifications.Enable"] = "Включить уведомления",
        ["Settings.Notifications.Motion"] = "События движения",
        ["Settings.Notifications.Detection"] = "Обнаружение объектов",
        ["Settings.Notifications.Cooldown"] = "Пауза на камеру (сек)",
        ["Settings.Notifications.QuietHours"] = "Тихие часы",
        ["Settings.Notifications.From"] = "С",
        ["Settings.Notifications.To"] = "до",

        ["Snapshot.Saved"] = "Сохранено →",
        ["Snapshot.Open"] = "Открыть",
        ["Snapshot.Copy"] = "Копировать",
        ["Snapshot.SaveAs"] = "Сохранить как…",

        ["CameraEditor.Title.Add"] = "Добавить камеру",
        ["CameraEditor.Title.Edit"] = "Редактировать камеру",
        ["CameraEditor.Label.Name"] = "Имя",
        ["CameraEditor.Label.Host"] = "Хост",
        ["CameraEditor.Label.HttpPort"] = "HTTP-порт",
        ["CameraEditor.Label.OnvifPort"] = "ONVIF-порт (необязательно)",
        ["CameraEditor.Label.RtspMain"] = "RTSP main URI",
        ["CameraEditor.Label.RtspSub"] = "RTSP sub URI (необязательно)",
        ["CameraEditor.Label.Username"] = "Логин",
        ["CameraEditor.Label.Password"] = "Пароль",
        ["CameraEditor.Label.Group"] = "Группа",
        ["CameraEditor.Label.SshSection"] = "SSH (необязательно)",
        ["CameraEditor.Label.StreamQuality"] = "Качество в гриде",
        ["CameraEditor.Quality.Auto"] = "Авто (SD/HD)",
        ["CameraEditor.Quality.AlwaysHd"] = "Всегда HD (main)",
        ["CameraEditor.Quality.AlwaysSd"] = "Всегда SD (sub)",
        ["CameraEditor.Analytics.Section"] = "ИИ-аналитика",
        ["CameraEditor.Analytics.Enable"] = "Включить детекцию объектов",
        ["CameraEditor.Analytics.Classes"] = "Классы",
        ["CameraEditor.Analytics.Threshold"] = "Порог уверенности",
        ["CameraEditor.Analytics.Fps"] = "Кадров/с анализа",
        ["CameraEditor.Analytics.AutoRecord"] = "Автозапись по детекции",
        ["CameraEditor.Analytics.PostEvent"] = "Дозапись после (с)",
        ["CameraEditor.Placeholder.Name"] = "Входная",
        ["CameraEditor.Placeholder.Host"] = "192.168.1.10",
        ["CameraEditor.Placeholder.OnvifPort"] = "8899",
        ["CameraEditor.Placeholder.RtspMain"] = "rtsp://192.168.1.10/",
        ["CameraEditor.Placeholder.RtspSub"] = "rtsp://192.168.1.10/stream1",
        ["CameraEditor.Placeholder.Username"] = "admin",
        ["CameraEditor.Placeholder.SshUser"] = "SSH-логин (пусто — как основной)",
        ["CameraEditor.Placeholder.SshPassword"] = "SSH-пароль (пусто — как основной)",
        ["CameraEditor.Placeholder.SshPort"] = "22",
        ["CameraEditor.NoGroup"] = "(без группы)",
        ["CameraEditor.Button.AutoDeriveRtsp"] = "Подставить из хоста",
        ["CameraEditor.Button.RtspTemplates"] = "Шаблоны ▾",
        ["CameraEditor.Tooltip.RtspTemplates"] = "Подставить RTSP-адреса под конкретного производителя камеры",
        ["CameraEditor.Button.TestConnection"] = "Проверить",
        ["CameraEditor.Status.Connecting"] = "Подключение…",
        ["CameraEditor.Status.OkFormat"] = "OK — {0}x{1}",
        ["CameraEditor.Status.Timeout"] = "Таймаут (8 с)",
        ["CameraEditor.Status.FailedFormat"] = "Ошибка: {0}",
        ["CameraEditor.Error.NameRequired"] = "Имя обязательно.",
        ["CameraEditor.Error.HostRequired"] = "Хост обязателен.",
        ["CameraEditor.Error.RtspMainInvalid"] = "RTSP main URI должен быть абсолютным URI.",
        ["CameraEditor.Error.RtspSubInvalid"] = "RTSP sub URI должен быть абсолютным URI.",
        ["CameraEditor.Error.OnvifPortInvalid"] = "ONVIF-порт должен быть от 1 до 65535.",
        ["CameraEditor.Error.HttpPortInvalid"] = "HTTP-порт должен быть от 1 до 65535.",
        ["CameraEditor.Error.SshPortInvalid"] = "SSH-порт должен быть от 1 до 65535.",
        ["CameraEditor.Error.SshCredsIncomplete"] = "Укажите и SSH-логин, и SSH-пароль, либо оставьте оба пустыми.",
        ["Terminal.Connecting"] = "Подключение…",
        ["Terminal.NoCreds"] = "Для камеры не заданы SSH-учётные данные.",
        ["Terminal.FailedFormat"] = "Ошибка SSH: {0}",
        ["Ssh.HostKeyChanged.Title"] = "SSH host-key изменился",
        ["Ssh.HostKeyChanged.Message"] = "SSH-ключ, который предъявил {0}, не совпадает с ранее сохранённым.\n\nНовый:      {1}\nСохранённый: {2}\n\nЭто нормально, если камеру перепрошили или заменили, — но может означать и перехват соединения. Доверять новому ключу и продолжить?",
        ["Ssh.HostKeyChanged.Trust"] = "Доверять ключу",
        ["FileManager.Title"] = "Файлы",
        ["FileManager.Connecting"] = "Подключение…",
        ["FileManager.NoCreds"] = "Для камеры не заданы SSH-учётные данные.",
        ["FileManager.FailedFormat"] = "Ошибка: {0}",
        ["FileManager.Refresh"] = "Обновить",
        ["FileManager.NewFolder"] = "Новая папка",
        ["FileManager.Upload"] = "Загрузить",
        ["FileManager.Download"] = "Скачать",
        ["FileManager.SaveTitle"] = "Сохранить файл как",
        ["FileManager.UploadTitle"] = "Выберите файл для загрузки",
        ["FileManager.NewFolderTitle"] = "Имя новой папки",
        ["FileManager.Downloading"] = "Скачивание…",
        ["FileManager.Uploading"] = "Загрузка…",
        ["FileManager.TransferDone"] = "Готово.",
        ["FileManager.DeleteProtected"] = "Удаление пути корневого уровня запрещено.",
        ["FileManager.DeleteTitle"] = "Удалить",
        ["FileManager.DeleteMessage"] = "Удалить «{0}» с камеры?",
        ["FileManager.Hint"] = "Папка — открыть, файл — скачать.",

        ["Discovery.Title"] = "Поиск камер",
        ["Discovery.Header"] = "Поиск ONVIF-камер",
        ["Discovery.Button.Scan"] = "Сканировать",
        ["Discovery.Button.AddSelected"] = "Добавить выбранные",
        ["Discovery.Status.Initial"] = "Нажмите «Сканировать» для поиска камер в сети (ONVIF + mDNS). «Глубокое сканирование» дополнительно обойдёт отмеченные подсети — включая доступные только через VPN.",
        ["Discovery.Status.Scanning"] = "Сканирование…",
        ["Discovery.Status.ScanningRangeFormat"] = "Сканирование {0} ({1} адр.)…",
        ["Discovery.Status.NoResponse"] = "Камеры не ответили. Проверьте multicast / фаервол.",
        ["Discovery.Status.FoundFormat"] = "Найдено камер: {0}.",
        ["Discovery.Status.Cancelled"] = "Сканирование отменено.",
        ["Discovery.Status.ScanFailedFormat"] = "Сканирование не удалось: {0}",
        ["Discovery.Status.ProbingFormat"] = "Опрос {0}…",
        ["Discovery.Status.ProbeOkFormat"] = "OK — {0} {1}",
        ["Discovery.Status.ProbeFailedFormat"] = "Опрос не удался: {0}",
        ["Discovery.Status.ManualAdd"] = "Без ONVIF — проверьте URL потока в редакторе.",
        ["Discovery.DeepScan"] = "Глубокое сканирование (медленнее)",
        ["Discovery.IpRange.Placeholder"] = "ещё диапазон, если нужен — 192.168.5.0/24, 10.0.0.10-60",
        ["Discovery.Target.DetailFormat"] = "{0} · {1} · адресов: {2}",
        ["Discovery.Target.Local"] = "сеть этого компьютера",
        ["Discovery.Target.Routed"] = "через маршрут — VPN или другой VLAN",
        ["Discovery.Sweep.SummaryFormat"] = "Глубокое сканирование обойдёт адресов: {0}.",
        ["Discovery.IpRange.Invalid"] = "Неверный диапазон IP. Например: 192.168.1.0/24, 192.168.1.10-200 или один адрес.",
        ["Discovery.IpRange.TooLargeFormat"] = "Слишком широкий диапазон — не более {0} адресов за один скан.",
        ["Discovery.UnknownModel"] = "(неизвестная модель)",
        ["Discovery.AlreadyAdded"] = "добавлена",
        ["Discovery.ReuseCreds"] = "Одни учётные данные для всех камер",
        ["Discovery.Confidence.Low"] = "низкая",
        ["Discovery.Confidence.Medium"] = "средняя",
        ["Discovery.Confidence.High"] = "высокая",

        ["RawConfigEditor.Title"] = "Правка raw-конфига Majestic",
        ["RawConfigEditor.InvalidJsonFormat"] = "Невалидный JSON: {0}",

        ["CameraPage.Rtmp.Toggle"] = "RTMP-push",
        ["CameraPage.Rtmp.UrlPlaceholder"] = "rtmp://сервер/stream-key",

        ["CameraPage.Majestic.Resolution"] = "Разр.",
        ["CameraPage.Majestic.Codec"] = "Кодек",
        ["CameraPage.Majestic.Fps"] = "FPS",
        ["CameraPage.Majestic.Bitrate"] = "Битрейт",
        ["CameraPage.Majestic.Profile"] = "Профиль",
        ["CameraPage.Majestic.NightPrefix"] = "ночь:",
        ["CameraPage.Majestic.ViewRaw"] = "Смотреть raw",
        ["CameraPage.Majestic.EditRaw"] = "Правка raw",
        ["CameraPage.Majestic.AllSettings"] = "Все настройки",
        ["CameraPage.Majestic.ApplyAll"] = "Применить настройки",
        ["CameraPage.Majestic.NoChanges"] = "Нет изменений для применения",
        ["CameraPage.Majestic.RestartHint"] = "Изменение перезапустит видеопоток",
        ["CameraPage.Majestic.Isp"] = "Живой ISP",
        ["CameraPage.Majestic.IspApply"] = "Применить ISP (на лету)",
        ["CameraPage.Majestic.IspApplied"] = "ISP применён — без рестарта",
        ["CameraPage.Majestic.IspEmpty"] = "Прошивка не предоставляет ISP-настроек.",
        ["CameraPage.Majestic.Metrics"] = "Метрики",
        ["CameraPage.Majestic.MetricsRefresh"] = "Обновить",
        ["CameraPage.Majestic.MetricsEmpty"] = "Метрики не получены.",
        ["CameraPage.Majestic.Search"] = "Фильтр полей…",
        ["CameraPage.Majestic.Revert"] = "Вернуть значение камеры",
        ["CameraPage.Majestic.RevertSection"] = "Сбросить секцию",
        ["CameraPage.Majestic.EditRawSsh"] = "Правка по SSH",
        ["CameraPage.SshNoCreds"] = "Для камеры не заданы SSH-учётные данные.",
        ["CameraPage.NightMode.Day"] = "День",
        ["CameraPage.NightMode.Night"] = "Ночь",
        ["CameraPage.NightMode.Auto"] = "Авто",
        ["CameraPage.Preset.Placeholder"] = "название пресета",
        ["CameraPage.Preset.Save"] = "+ Сохранить",
        ["CameraPage.Snapshot"] = "Снимок",
        ["CameraPage.Stop"] = "■ Стоп",
        ["CameraPage.ApplyingStatus"] = "Применение…",
        ["CameraPage.ApplyingRawStatus"] = "Применение raw-конфига…",
        ["CameraPage.AppliedRestarting"] = "Применено. Перезапуск потока…",
        ["CameraPage.ApplyDone"] = "Готово.",
        ["CameraPage.ApplyFailedFormat"] = "Ошибка: {0}",
        ["CameraPage.RecordingFailedFormat"] = "Запись не удалась: {0}",
        ["CameraPage.SnapshotFailedFormat"] = "Снимок не удался: {0}",
        ["CameraPage.Tooltip.Listen"] = "Слушать звук с камеры",
        ["CameraPage.Tooltip.Mute"] = "Выключить звук",
        ["CameraPage.Tooltip.Volume"] = "Громкость",
        ["CameraPage.Audio.DisabledHint"] = "Звук на камере выключен",
        ["CameraPage.Audio.Enable"] = "Включить звук",
        ["CameraPage.Audio.Enabling"] = "Включение…",
        ["CameraPage.Tooltip.Talk"] = "Говорить в камеру (рация)",
        ["CameraPage.Talk.Unsupported"] = "У этой камеры нет двусторонней связи.",
        ["CameraPage.OpenSnapshotFailedFormat"] = "Не удалось открыть снимок: {0}",
        ["CameraPage.CopySnapshotFailedFormat"] = "Не удалось скопировать снимок: {0}",
        ["CameraPage.SaveSnapshotFailedFormat"] = "Не удалось сохранить снимок: {0}",
        ["CameraPage.Tooltip.RemovePreset"] = "Удалить пресет",

        ["Snapshot.SaveAsTitle"] = "Сохранить снимок",

        ["Snapshots.Title"] = "Снимки",
        ["Snapshots.AllCameras"] = "Все камеры",
        ["Snapshots.PresetAll"] = "Все",
        ["Snapshots.PresetToday"] = "Сегодня",
        ["Snapshots.Preset7"] = "7 дней",
        ["Snapshots.Preset30"] = "30 дней",
        ["Snapshots.SortNewest"] = "Сначала новые",
        ["Snapshots.SortOldest"] = "Сначала старые",
        ["Snapshots.Empty"] = "Снимков пока нет",
        ["Snapshots.LoadError"] = "Не удалось загрузить снимки",
        ["Snapshots.SelectedFormat"] = "Выбрано: {0}",
        ["Snapshots.Dialog.DeleteTitle"] = "Удаление снимков",
        ["Snapshots.Dialog.DeleteOneMessage"] = "Удалить этот снимок? Действие необратимо.",
        ["Snapshots.Dialog.DeleteManyMessageFormat"] = "Удалить снимков: {0}? Действие необратимо.",

        ["Viewer.ZoomIn"] = "Увеличить",
        ["Viewer.ZoomOut"] = "Уменьшить",
        ["Viewer.Fit"] = "Вписать",
        ["Viewer.RotateLeft"] = "Повернуть влево",
        ["Viewer.RotateRight"] = "Повернуть вправо",
        ["Viewer.FlipH"] = "Отразить по горизонтали",
        ["Viewer.FlipV"] = "Отразить по вертикали",
        ["Viewer.Slideshow"] = "Слайд-шоу",
        ["Viewer.Copy"] = "Копировать",
        ["Viewer.Properties"] = "Детали",
        ["Viewer.Prev"] = "Назад",
        ["Viewer.Next"] = "Вперёд",
        ["Viewer.Edit"] = "Редактор",
        ["Viewer.Share"] = "Поделиться",
        ["Viewer.Reveal"] = "Показать в папке",
        ["Snapshots.Share"] = "Поделиться",
        ["Snapshots.Reveal"] = "Показать в папке",

        ["Edit.Arrow"] = "Стрелка",
        ["Edit.Rect"] = "Рамка",
        ["Edit.Text"] = "Текст",
        ["Edit.Crop"] = "Обрезка",
        ["Edit.Undo"] = "Отменить",
        ["Edit.Save"] = "Сохранить копию",
        ["Edit.TextPrompt"] = "Текст подписи",
        ["Edit.AddText"] = "Добавить",

        ["Grid.EmptySlot"] = "нет камеры",
        ["Grid.Tooltip.Fullscreen"] = "Сетка на весь экран (F11) — Esc для выхода",
        ["Grid.Tooltip.Stills"] = "Режим кадров — периодические снимки вместо живого видео",
        ["Tile.Snapshot"] = "Снимок (HD)",

        ["Welcome.Language"] = "Язык",

        ["Recordings.Dialog.DeleteTitle"] = "Удалить запись",
        ["Recordings.Dialog.DeleteMessageFormat"] = "Удалить {0}? MP4-файл будет удалён.",
        ["Recordings.Empty"] = "Записей пока нет. Нажмите ● REC на странице камеры, чтобы начать.",
        ["Recordings.Live"] = "идёт",
        ["Recordings.LoadError"] = "Не удалось загрузить записи",
        ["Recordings.MarkIn"] = "Начало",
        ["Recordings.MarkOut"] = "Конец",
        ["Recordings.Precise"] = "Точно",
        ["Recordings.Export"] = "Экспорт",
        ["Recordings.ExportTitle"] = "Экспорт клипа",

        ["Events.Button.SimulateMotion"] = "Симулировать движение",
        ["Events.Empty"] = "Событий пока нет. Нажмите «Симулировать движение», чтобы прогнать одно через конвейер.",
        ["Events.AllCameras"] = "Все камеры",
        ["Events.Open"] = "открыто",

        ["Lang.System"] = "Системный",
        ["Lang.English"] = "English",
        ["Lang.Russian"] = "Русский",
    };
}

public enum LangCode
{
    System = 0,
    English,
    Russian,
}
