// EN/RU strings for the SPA — originally ported from the Phase 20 WebStrings.cs
// (since removed along with the Razor UI), so this is now the only UI string
// table: the backend carries none.
type Dict = Record<string, string>

export const EN: Dict = {
  'Login.Subtitle': 'Sign in to the web console',
  'Login.Username': 'Username',
  'Login.Password': 'Password',
  'Login.SignIn': 'Sign in',
  'Login.Error': 'Invalid username or password.',

  'Nav.Cameras': 'Cameras',
  'Nav.Grid': 'Grid',
  'Nav.Groups': 'Groups',
  'Nav.Discovery': 'Discovery',
  'Nav.Recordings': 'Archive',
  'Nav.Users': 'Users',
  'Nav.Settings': 'Settings',
  'Nav.System': 'System',
  'Nav.SignOut': 'Sign out',

  'System.Title': 'System',
  'System.Version': 'Version',
  'System.Cameras': 'Cameras',
  'System.Groups': 'Groups',
  'System.Sessions': 'Active sessions',
  'System.Streams': 'Live streams',
  'System.Backup': 'Backup & restore',
  'System.Export': 'Export config',
  'System.ImportBtn': 'Import',
  'System.BackupNote':
    'Export writes a JSON backup of cameras, groups and layouts. Camera passwords are never included.',
  'System.Imported': 'Imported:',
  'System.ImportError': 'Import failed — check the file.',
  'System.SessionsTitle': 'Sessions',
  'System.RevokeAll': 'Sign out all sessions',
  'System.RevokeConfirm': 'Sign out every session, including this one?',

  'Cameras.Title': 'Cameras',
  'Cameras.Add': 'Add camera',
  'Cameras.Empty': 'No cameras yet.',
  'Common.Loading': 'Loading…',
  'Common.Save': 'Save',
  'Common.Cancel': 'Cancel',
  'Common.Close': 'Close',
  'Common.Seconds': 's',
  'Cameras.Th.Name': 'Name',
  'Cameras.Th.Host': 'Host',
  'Cameras.Th.Group': 'Group',
  'Cameras.Th.Grid': 'Grid',
  'Cameras.Live': 'Live',
  'Cameras.Edit': 'Edit',
  'Cameras.Delete': 'Delete',
  'Cameras.DeleteConfirm': 'Delete this camera?',
  'Common.Yes': 'yes',
  'Common.No': 'no',

  'Editor.AddTitle': 'Add camera',
  'Editor.EditTitle': 'Edit camera',
  'Editor.Error':
    'Please check the fields — name, host and a valid RTSP URL are required.',
  'Editor.Name': 'Name',
  'Editor.Host': 'Host',
  'Editor.RtspMain': 'RTSP main URL',
  'Editor.RtspSub': 'RTSP sub URL (optional)',
  'Editor.HttpPort': 'HTTP port',
  'Editor.OnvifPort': 'ONVIF port',
  'Editor.Group': 'Group',
  'Editor.NoGroup': '(no group)',
  'Editor.Quality': 'Stream quality',
  'Editor.Username': 'Username',
  'Editor.Password': 'Password',
  'Editor.KeepBlank': 'leave blank to keep',
  'Editor.Optional': 'optional',
  'Editor.Save': 'Save',
  'Editor.Add': 'Add camera',
  'Editor.Cancel': 'Cancel',

  'Grid.Title': 'Grid',
  'Grid.Empty': 'No cameras to show. Add cameras or include them in the grid.',
  'Grid.NewLayout': 'Layout',
  'Grid.NewLayoutTitle': 'New layout',
  'Grid.NewLayoutName': 'New layout name',
  'Grid.Edit': 'Edit layout',
  'Grid.Rename': 'Rename',
  'Grid.DeleteLayout': 'Delete layout',
  'Grid.DeleteLayoutConfirm': 'Delete this layout?',
  'Grid.Size': 'Size',
  'Grid.EmptyCell': '(empty)',
  'Grid.NoLayouts': 'No layouts yet — create one.',
  'Grid.Single': 'Single camera',
  'Grid.PrevPage': 'Previous page',
  'Grid.NextPage': 'Next page',
  'Grid.EditingPage': 'Editing page',
  'Grid.Stills': 'Stills',
  'Grid.StillsHint': 'Periodic snapshots instead of live streams — much lighter for a big wall',
  'Grid.StillsInterval': 'Refresh interval',
  'Grid.StillFailed': 'no frame',
  'Grid.Kiosk': 'Kiosk',
  'Grid.KioskHint': 'Full-screen wall without the interface (Esc to leave)',
  'Grid.KioskExit': 'Leave kiosk',
  'Grid.Rotate': 'Cycle pages',

  'Groups.Title': 'Groups',
  'Groups.Add': 'Add group',
  'Groups.Name': 'Name',
  'Groups.NewName': 'Group name',
  'Groups.Empty': 'No groups yet.',
  'Groups.Rename': 'Rename group',
  'Groups.DeleteConfirm': 'Delete this group?',
  'Groups.InUse': 'Group is still used by cameras.',
  'System.Account': 'Account',

  'Live.Back': 'Cameras',
  'Camera.Details': 'Details',
  'Camera.Credentials': 'Credentials set',
  'Camera.Capabilities': 'Capabilities',
  'Camera.Chip': 'Chip',
  'Camera.Firmware': 'Firmware',

  'Ptz.Title': 'PTZ control',
  'Ptz.Up': 'Up',
  'Ptz.Down': 'Down',
  'Ptz.Left': 'Left',
  'Ptz.Right': 'Right',
  'Ptz.UpLeft': 'Up-left',
  'Ptz.UpRight': 'Up-right',
  'Ptz.DownLeft': 'Down-left',
  'Ptz.DownRight': 'Down-right',
  'Ptz.Stop': 'Stop',
  'Ptz.Home': 'Home position',
  'Ptz.Zoom': 'Zoom',
  'Ptz.ZoomIn': 'Zoom in',
  'Ptz.ZoomOut': 'Zoom out',
  'Ptz.Speed': 'Speed',
  'Ptz.Presets': 'Presets',
  'Ptz.PresetName': 'New preset',
  'Ptz.PresetSave': 'Save',
  'Ptz.PresetDelete': 'Delete preset',
  'Ptz.Error': 'The camera did not accept the PTZ command.',

  'Discovery.Title': 'Discovery',
  'Discovery.Scan': 'Scan',
  'Discovery.Stop': 'Stop',
  'Discovery.DeepScan': 'Deep scan',
  'Discovery.DeepScanNote':
    'Passive sources (ONVIF, mDNS) always run. Deep scan also sweeps the local subnet — it finds cameras that announce nothing, but looks like a port scan on the network.',
  'Discovery.IpRange': 'IP range',
  'Discovery.IpRangePlaceholder': '192.168.1.0/24 (optional)',
  'Discovery.IpRangeNote':
    'Leave the range blank to sweep the server’s own subnet. Fill it in — 192.168.1.0/24, 192.168.1.10-200, a single address, or several separated by commas — to sweep somewhere else; that also switches the sweep on by itself.',
  'Discovery.IpRangeInvalid': 'That IP range is not valid.',
  'Discovery.Scanning': 'Scanning…',
  'Discovery.Found': 'Found:',
  'Discovery.Nothing': 'Nothing answered. Try a deep scan, or add the camera by hand.',
  'Discovery.Cancelled': 'Scan cancelled.',
  'Discovery.Failed': 'Scan failed.',
  'Discovery.Busy': 'A scan is already running.',
  'Discovery.Th.Device': 'Device',
  'Discovery.Th.Host': 'Address',
  'Discovery.Th.Signals': 'Found via',
  'Discovery.Confidence.High': 'identified',
  'Discovery.Confidence.Medium': 'probably a camera',
  'Discovery.Confidence.Low': 'maybe',
  'Discovery.AlreadyAdded': 'already added',
  'Discovery.Add': 'Add',
  'Discovery.AddTitle': 'Add camera',
  'Discovery.Probe': 'Probe',
  'Discovery.ProbeFirst': 'probe, or type the RTSP URL',
  'Discovery.ProbeFailed': 'Probe failed.',
  'Discovery.NoOnvif': 'No ONVIF answer — check the login, or add it with the RTSP URL below.',
  'Discovery.AddFailed': 'Could not add the camera.',

  'Users.Title': 'Users',
  'Users.Add': 'Add user',
  'Users.AddTitle': 'Add user',
  'Users.EditTitle': 'Edit user',
  'Users.Empty': 'No users yet — only the built-in administrator can sign in.',
  'Users.Unavailable': 'This server runs without a user roster, so only the built-in administrator can sign in.',
  'Users.BootstrapNote':
    'The built-in administrator ({user}) always keeps full access — it is the way back in if an account is lost.',
  'Users.Th.Name': 'Name',
  'Users.Th.Permissions': 'May do',
  'Users.Th.Cameras': 'Cameras',
  'Users.AllCameras': 'All cameras',
  'Users.DeleteConfirm': 'Delete this user?',
  'Users.Exists': 'A user with that name already exists.',
  'Users.SaveFailed': 'Could not save the user.',
  'Users.Perm.ViewLive': 'watch live',
  'Users.Perm.ViewArchive': 'watch archive',
  'Users.Perm.Ptz': 'PTZ',
  'Users.Perm.Export': 'export',
  'Users.Perm.Manage': 'manage',

  'Tile.Listen': 'Listen',
  'Tile.Mute': 'Mute',
  'Majestic.Title': 'Camera settings',
  'Majestic.Reload': 'Reload',
  'Majestic.NightMode': 'Day/night',
  'Majestic.Night.day': 'Day',
  'Majestic.Night.night': 'Night',
  'Majestic.Night.auto': 'Auto',
  'Majestic.Isp': 'Image (live)',
  'Majestic.IspHint': 'Applied on the fly — the stream does not restart',
  'Majestic.ApplyIsp': 'Apply',
  'Majestic.Config': 'Configuration',
  'Majestic.Filter': 'Filter…',
  'Majestic.Changed': 'Changed',
  'Majestic.Revert': 'Revert',
  'Majestic.NoMatches': 'Nothing matches the filter.',
  'Majestic.NoChanges': 'Nothing changed.',
  'Majestic.Applied': 'Applied.',
  'Majestic.AppliedRestart': 'Applied — the camera restarts the stream, the tile will blink.',
  'Majestic.ApplyFailed': 'The camera rejected the change.',
  'Majestic.RestartHint': 'Changing this restarts the video stream',
  'Majestic.Metrics': 'Metrics',
  'Majestic.NoMetrics': 'This firmware has no /metrics endpoint.',
  'Majestic.Raw': 'Raw config.json',
  'Majestic.RawHint': 'The whole file, as the camera holds it. No validation beyond "is it JSON" — same as editing it over SSH.',
  'Majestic.BadJson': 'Not valid JSON',
  'Majestic.NotMajestic': 'This camera does not run Majestic.',
  'Majestic.Unreachable': 'The camera did not answer.',
  'Recordings.Tab': 'Recordings',
  'Snapshots.Title': 'Snapshots',
  'Snapshots.Empty': 'No saved snapshots yet.',
  'Snapshots.Delete': 'Delete snapshot',
  'Snapshots.DeleteConfirm': 'Delete this snapshot from the library?',
  'Snapshot.Save': 'Save to library',
  'Snapshot.Saved': 'Saved to the library.',
  'Snapshot.SaveFailed': 'Could not save the snapshot.',
  'Talk.Title': 'Talk',
  'Talk.Hold': 'Hold to talk',
  'Talk.Talking': 'On air…',
  'Talk.Unsupported': 'This camera has no speaker.',
  'Talk.Busy': 'Someone else is talking to this camera.',
  'Talk.Failed': 'The camera did not accept the audio.',
  'Talk.NoMic': 'No microphone, or access was denied.',
  'Talk.NeedsHttps': 'Talking needs a microphone, which browsers only allow over HTTPS (or on localhost).',
  'Users.Perm.Talk': 'talk',
  'Tile.Fullscreen': 'Fullscreen',
  'Tile.ZoomIn': 'Zoom in (mouse wheel)',
  'Tile.ZoomOut': 'Zoom out',
  'Tile.ZoomReset': 'Reset zoom',
  'Snapshot.Take': 'Snapshot',
  'Snapshot.Taking': 'Asking the camera for a still…',
  'Snapshot.Download': 'Download',
  'Snapshot.Failed': 'The camera did not return a still.',

  'Recording.Start': 'Record',
  'Recording.Stop': 'Stop recording',
  'Recording.Active': 'recording',
  'Recording.Nothing': 'The camera sent nothing — no clip was saved.',
  'Recording.Failed': 'Could not start recording.',

  'Export.MarkIn': 'Mark in',
  'Export.MarkOut': 'Mark out',
  'Export.Save': 'Export clip',
  'Export.Precise': 'exact frame (re-encodes)',

  'Archive.PrevMonth': 'Previous month',
  'Archive.NextMonth': 'Next month',
  'Archive.ClearDay': 'Whole archive',
  'Archive.EmptyDay': 'Nothing recorded on this day.',

  'Recordings.Title': 'Archive',
  'Recordings.AllCameras': 'All cameras',
  'Recordings.Empty': 'Nothing recorded yet. Recording is started from the desktop app.',
  'Recordings.Th.Camera': 'Camera',
  'Recordings.Th.Started': 'Started',
  'Recordings.Th.Duration': 'Length',
  'Recordings.Th.Size': 'Size',
  'Recordings.Play': 'Play',
  'Recordings.Download': 'Download',
  'Recordings.Motion': 'motion',
  'Recordings.NotPlayableHint': 'This codec does not play in most browsers — download the file instead.',
  'Recordings.DeleteConfirm': 'Delete this recording? The file is removed from disk.',
}

export const RU: Dict = {
  'Login.Subtitle': 'Вход в веб-консоль',
  'Login.Username': 'Логин',
  'Login.Password': 'Пароль',
  'Login.SignIn': 'Войти',
  'Login.Error': 'Неверный логин или пароль.',

  'Nav.Cameras': 'Камеры',
  'Nav.Grid': 'Сетка',
  'Nav.Groups': 'Группы',
  'Nav.Discovery': 'Поиск',
  'Nav.Recordings': 'Архив',
  'Nav.Users': 'Пользователи',
  'Nav.Settings': 'Настройки',
  'Nav.System': 'Система',
  'Nav.SignOut': 'Выход',

  'System.Title': 'Система',
  'System.Version': 'Версия',
  'System.Cameras': 'Камеры',
  'System.Groups': 'Группы',
  'System.Sessions': 'Активные сессии',
  'System.Streams': 'Живые потоки',
  'System.Backup': 'Бэкап и восстановление',
  'System.Export': 'Экспорт конфига',
  'System.ImportBtn': 'Импорт',
  'System.BackupNote':
    'Экспорт пишет JSON-бэкап камер, групп и раскладок. Пароли камер не включаются.',
  'System.Imported': 'Импортировано:',
  'System.ImportError': 'Импорт не удался — проверьте файл.',
  'System.SessionsTitle': 'Сессии',
  'System.RevokeAll': 'Завершить все сессии',
  'System.RevokeConfirm': 'Завершить все сессии, включая текущую?',

  'Cameras.Title': 'Камеры',
  'Cameras.Add': 'Добавить камеру',
  'Cameras.Empty': 'Камер пока нет.',
  'Common.Loading': 'Загрузка…',
  'Common.Seconds': 'с',
  'Common.Save': 'Сохранить',
  'Common.Cancel': 'Отмена',
  'Common.Close': 'Закрыть',
  'Cameras.Th.Name': 'Имя',
  'Cameras.Th.Host': 'Хост',
  'Cameras.Th.Group': 'Группа',
  'Cameras.Th.Grid': 'Сетка',
  'Cameras.Live': 'Эфир',
  'Cameras.Edit': 'Изменить',
  'Cameras.Delete': 'Удалить',
  'Cameras.DeleteConfirm': 'Удалить камеру?',
  'Common.Yes': 'да',
  'Common.No': 'нет',

  'Editor.AddTitle': 'Добавить камеру',
  'Editor.EditTitle': 'Изменить камеру',
  'Editor.Error': 'Проверьте поля — нужны имя, хост и корректный RTSP URL.',
  'Editor.Name': 'Имя',
  'Editor.Host': 'Хост',
  'Editor.RtspMain': 'RTSP main URL',
  'Editor.RtspSub': 'RTSP sub URL (необязательно)',
  'Editor.HttpPort': 'HTTP-порт',
  'Editor.OnvifPort': 'ONVIF-порт',
  'Editor.Group': 'Группа',
  'Editor.NoGroup': '(без группы)',
  'Editor.Quality': 'Качество потока',
  'Editor.Username': 'Логин',
  'Editor.Password': 'Пароль',
  'Editor.KeepBlank': 'пусто = не менять',
  'Editor.Optional': 'необязательно',
  'Editor.Save': 'Сохранить',
  'Editor.Add': 'Добавить камеру',
  'Editor.Cancel': 'Отмена',

  'Grid.Title': 'Сетка',
  'Grid.Empty': 'Нет камер для показа. Добавьте камеры или включите их в сетку.',
  'Grid.NewLayout': 'Раскладка',
  'Grid.NewLayoutTitle': 'Новая раскладка',
  'Grid.NewLayoutName': 'Название новой раскладки',
  'Grid.Edit': 'Изменить раскладку',
  'Grid.Rename': 'Переименовать',
  'Grid.DeleteLayout': 'Удалить раскладку',
  'Grid.DeleteLayoutConfirm': 'Удалить эту раскладку?',
  'Grid.Size': 'Размер',
  'Grid.EmptyCell': '(пусто)',
  'Grid.NoLayouts': 'Раскладок пока нет — создайте.',
  'Grid.Single': 'Одна камера',
  'Grid.PrevPage': 'Предыдущая страница',
  'Grid.NextPage': 'Следующая страница',
  'Grid.EditingPage': 'Редактируется страница',
  'Grid.Stills': 'Стоп-кадры',
  'Grid.StillsHint': 'Периодические снимки вместо живых потоков — намного легче для большой стены',
  'Grid.StillsInterval': 'Интервал обновления',
  'Grid.StillFailed': 'нет кадра',
  'Grid.Kiosk': 'Киоск',
  'Grid.KioskHint': 'Полноэкранная стена без интерфейса (выход — Esc)',
  'Grid.KioskExit': 'Выйти из киоска',
  'Grid.Rotate': 'Листать страницы',

  'Groups.Title': 'Группы',
  'Groups.Add': 'Добавить группу',
  'Groups.Name': 'Имя',
  'Groups.NewName': 'Название группы',
  'Groups.Empty': 'Групп пока нет.',
  'Groups.Rename': 'Переименовать группу',
  'Groups.DeleteConfirm': 'Удалить группу?',
  'Groups.InUse': 'Группа ещё используется камерами.',
  'System.Account': 'Учётная запись',

  'Live.Back': 'Камеры',
  'Camera.Details': 'Детали',
  'Camera.Credentials': 'Учётные данные заданы',
  'Camera.Capabilities': 'Возможности',
  'Camera.Chip': 'Чип',
  'Camera.Firmware': 'Прошивка',

  'Ptz.Title': 'Управление PTZ',
  'Ptz.Up': 'Вверх',
  'Ptz.Down': 'Вниз',
  'Ptz.Left': 'Влево',
  'Ptz.Right': 'Вправо',
  'Ptz.UpLeft': 'Вверх-влево',
  'Ptz.UpRight': 'Вверх-вправо',
  'Ptz.DownLeft': 'Вниз-влево',
  'Ptz.DownRight': 'Вниз-вправо',
  'Ptz.Stop': 'Стоп',
  'Ptz.Home': 'Домашняя позиция',
  'Ptz.Zoom': 'Зум',
  'Ptz.ZoomIn': 'Приблизить',
  'Ptz.ZoomOut': 'Отдалить',
  'Ptz.Speed': 'Скорость',
  'Ptz.Presets': 'Пресеты',
  'Ptz.PresetName': 'Новый пресет',
  'Ptz.PresetSave': 'Сохранить',
  'Ptz.PresetDelete': 'Удалить пресет',
  'Ptz.Error': 'Камера не приняла команду PTZ.',

  'Discovery.Title': 'Поиск камер',
  'Discovery.Scan': 'Искать',
  'Discovery.Stop': 'Стоп',
  'Discovery.DeepScan': 'Глубокий скан',
  'Discovery.DeepScanNote':
    'Пассивные источники (ONVIF, mDNS) работают всегда. Глубокий скан дополнительно обходит подсеть — найдёт камеры, которые о себе не заявляют, но со стороны выглядит как сканирование портов.',
  'Discovery.IpRange': 'Диапазон IP',
  'Discovery.IpRangePlaceholder': '192.168.1.0/24 (необязательно)',
  'Discovery.IpRangeNote':
    'Пустое поле — обходится подсеть самого сервера. Укажите диапазон — 192.168.1.0/24, 192.168.1.10-200, один адрес или несколько через запятую — чтобы обойти другую сеть; это само по себе включает обход.',
  'Discovery.IpRangeInvalid': 'Неверный диапазон IP.',
  'Discovery.Scanning': 'Идёт поиск…',
  'Discovery.Found': 'Найдено:',
  'Discovery.Nothing': 'Никто не ответил. Попробуйте глубокий скан или добавьте камеру вручную.',
  'Discovery.Cancelled': 'Поиск отменён.',
  'Discovery.Failed': 'Поиск не удался.',
  'Discovery.Busy': 'Поиск уже идёт.',
  'Discovery.Th.Device': 'Устройство',
  'Discovery.Th.Host': 'Адрес',
  'Discovery.Th.Signals': 'Как найдено',
  'Discovery.Confidence.High': 'опознана',
  'Discovery.Confidence.Medium': 'скорее всего камера',
  'Discovery.Confidence.Low': 'возможно',
  'Discovery.AlreadyAdded': 'уже добавлена',
  'Discovery.Add': 'Добавить',
  'Discovery.AddTitle': 'Добавить камеру',
  'Discovery.Probe': 'Опросить',
  'Discovery.ProbeFirst': 'опросите камеру или впишите RTSP URL',
  'Discovery.ProbeFailed': 'Опрос не удался.',
  'Discovery.NoOnvif': 'ONVIF не ответил — проверьте логин или добавьте камеру по RTSP URL ниже.',
  'Discovery.AddFailed': 'Не удалось добавить камеру.',

  'Users.Title': 'Пользователи',
  'Users.Add': 'Добавить пользователя',
  'Users.AddTitle': 'Добавить пользователя',
  'Users.EditTitle': 'Изменить пользователя',
  'Users.Empty': 'Пользователей пока нет — войти может только встроенный администратор.',
  'Users.Unavailable': 'Сервер запущен без списка пользователей, войти может только встроенный администратор.',
  'Users.BootstrapNote':
    'Встроенный администратор ({user}) всегда сохраняет полный доступ — это способ вернуться, если аккаунт потерян.',
  'Users.Th.Name': 'Имя',
  'Users.Th.Permissions': 'Права',
  'Users.Th.Cameras': 'Камеры',
  'Users.AllCameras': 'Все камеры',
  'Users.DeleteConfirm': 'Удалить пользователя?',
  'Users.Exists': 'Пользователь с таким именем уже есть.',
  'Users.SaveFailed': 'Не удалось сохранить пользователя.',
  'Users.Perm.ViewLive': 'смотреть эфир',
  'Users.Perm.ViewArchive': 'смотреть архив',
  'Users.Perm.Ptz': 'PTZ',
  'Users.Perm.Export': 'экспорт',
  'Users.Perm.Manage': 'управление',

  'Tile.Listen': 'Слушать',
  'Tile.Mute': 'Выключить звук',
  'Majestic.Title': 'Настройки камеры',
  'Majestic.Reload': 'Обновить',
  'Majestic.NightMode': 'День/ночь',
  'Majestic.Night.day': 'День',
  'Majestic.Night.night': 'Ночь',
  'Majestic.Night.auto': 'Авто',
  'Majestic.Isp': 'Изображение (на лету)',
  'Majestic.IspHint': 'Применяется на лету — поток не перезапускается',
  'Majestic.ApplyIsp': 'Применить',
  'Majestic.Config': 'Конфигурация',
  'Majestic.Filter': 'Фильтр…',
  'Majestic.Changed': 'Изменено',
  'Majestic.Revert': 'Вернуть',
  'Majestic.NoMatches': 'Ничего не найдено.',
  'Majestic.NoChanges': 'Изменений нет.',
  'Majestic.Applied': 'Применено.',
  'Majestic.AppliedRestart': 'Применено — камера перезапускает поток, тайл моргнёт.',
  'Majestic.ApplyFailed': 'Камера не приняла изменение.',
  'Majestic.RestartHint': 'Изменение перезапускает видеопоток',
  'Majestic.Metrics': 'Метрики',
  'Majestic.NoMetrics': 'В этой прошивке нет эндпоинта /metrics.',
  'Majestic.Raw': 'Сырой config.json',
  'Majestic.RawHint': 'Файл целиком, как его хранит камера. Проверяется только то, что это JSON — как при правке по SSH.',
  'Majestic.BadJson': 'Некорректный JSON',
  'Majestic.NotMajestic': 'На этой камере нет Majestic.',
  'Majestic.Unreachable': 'Камера не ответила.',
  'Recordings.Tab': 'Записи',
  'Snapshots.Title': 'Снимки',
  'Snapshots.Empty': 'Сохранённых снимков пока нет.',
  'Snapshots.Delete': 'Удалить снимок',
  'Snapshots.DeleteConfirm': 'Удалить этот снимок из библиотеки?',
  'Snapshot.Save': 'Сохранить в архив',
  'Snapshot.Saved': 'Сохранено в архив.',
  'Snapshot.SaveFailed': 'Не удалось сохранить снимок.',
  'Talk.Title': 'Говорить',
  'Talk.Hold': 'Удерживайте, чтобы говорить',
  'Talk.Talking': 'В эфире…',
  'Talk.Unsupported': 'У этой камеры нет динамика.',
  'Talk.Busy': 'С этой камерой уже кто-то говорит.',
  'Talk.Failed': 'Камера не приняла звук.',
  'Talk.NoMic': 'Микрофона нет, или доступ к нему запрещён.',
  'Talk.NeedsHttps': 'Для разговора нужен микрофон, а браузер даёт его только по HTTPS (или на localhost).',
  'Users.Perm.Talk': 'говорить',
  'Tile.Fullscreen': 'Во весь экран',
  'Tile.ZoomIn': 'Приблизить (колесо мыши)',
  'Tile.ZoomOut': 'Отдалить',
  'Tile.ZoomReset': 'Сбросить зум',
  'Snapshot.Take': 'Снимок',
  'Snapshot.Taking': 'Запрашиваем кадр у камеры…',
  'Snapshot.Download': 'Скачать',
  'Snapshot.Failed': 'Камера не отдала кадр.',

  'Recording.Start': 'Записать',
  'Recording.Stop': 'Остановить запись',
  'Recording.Active': 'идёт запись',
  'Recording.Nothing': 'Камера ничего не передала — запись не сохранена.',
  'Recording.Failed': 'Не удалось начать запись.',

  'Export.MarkIn': 'Начало',
  'Export.MarkOut': 'Конец',
  'Export.Save': 'Сохранить фрагмент',
  'Export.Precise': 'точный кадр (перекодирование)',

  'Archive.PrevMonth': 'Предыдущий месяц',
  'Archive.NextMonth': 'Следующий месяц',
  'Archive.ClearDay': 'Весь архив',
  'Archive.EmptyDay': 'В этот день ничего не записано.',

  'Recordings.Title': 'Архив',
  'Recordings.AllCameras': 'Все камеры',
  'Recordings.Empty': 'Записей пока нет. Запись запускается из десктоп-приложения.',
  'Recordings.Th.Camera': 'Камера',
  'Recordings.Th.Started': 'Начало',
  'Recordings.Th.Duration': 'Длительность',
  'Recordings.Th.Size': 'Размер',
  'Recordings.Play': 'Смотреть',
  'Recordings.Download': 'Скачать',
  'Recordings.Motion': 'движение',
  'Recordings.NotPlayableHint': 'Этот кодек не играет в большинстве браузеров — скачайте файл.',
  'Recordings.DeleteConfirm': 'Удалить запись? Файл будет удалён с диска.',
}
